### ISSUE TITLE
Warning in logs

### ISSUE THREAD

**Issue by pamae** [danielrivard/homeassistant-innova#172]
WARNING (MainThread) [homeassistant.components.climate] Entity None (<class 'custom_components.innova.climate.InnovaEntity'>) implements HVACMode(s): off, heat, cool, dry, fan_only, heat_cool and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature.

**Comment by danielrivard** [comment]
Thanks for the report. I will look into it soon.
