### ISSUE TITLE
How to configure multiple units

### ISSUE THREAD

**Issue by cybert79** [danielrivard/homeassistant-innova#2]
@danielrivard Thanks allready for this amazing job!

To configure multiple units, and be able to control each unit (note that platform must be there for each unit!):

climate:
  - platform: innova
    host: 192.168.1.134
    scan_interval: 1200
  - platform: innova
    host: 192.168.1.126
    scan_interval: 1200
  - platform: innova
     host: 192.168.1.129
     scan_interval: 1200

**Comment by danielrivard** [comment]
Thanks for the tip, I only have one unit at home, so I cannot really test that scenario.

The integration does assign the HA `unique_id` property using the serial number of the unit when updating the status. The name is also set to what have been set through the Innova App. So they should be seen as different entities by HA.

**Comment by cybert79** [comment]
Well, I have noticed if you don't add the - platform, you cannot set the temperature for an individual thermostate card

**Comment by danielrivard** [comment]
I modified the documentation to indicate more than one unit configured.
