### ISSUE TITLE
AirLeaf with simil serial no.

### ISSUE THREAD

**Issue by WileCoyote76** [danielrivard/homeassistant-innova#205]
Hi,
I have two AirLeafs with "Serial No." similar.
When I configure the second one the first one disconnects.
To be precise the two "Serial No." end with the same 6 digits.
This is very strange because in the configuration I don't enter the serial number but only the IP address.

**Comment by danielrivard** [comment]
Unfortunately, this is not the first time this happens, the way they set the serial number is not optimal. The way to fix it would be to use the MAC address as a unique id instead, but I need to find a way to do that without breaking existing installation.

You can see this comment to where there is a way to fix it. 

https://github.com/danielrivard/homeassistant-innova/issues/187#issuecomment-2040065106

I should probably at this in the README documentation.
