### ISSUE TITLE
circuit numbering in multiple circuits system

### ISSUE THREAD

**Issue by peedign** [danielrivard/homeassistant-innova#233]
**Is your feature request related to a problem? Please describe.**
it looks to me, that circuit/zone numbering in HA and MyVaillant is not the same (ie HA starts from circuit 0 MyVaillant is from 1)

**Describe the solution you'd like**
it would be great to align the numbering as it is very confusing to match the circuits manually in larger systems

**Additional context**
<img width="251" alt="image" src="https://github.com/user-attachments/assets/db4d6bd7-ac4a-4a93-9d29-4bd0bd5ab276">

![Screenshot_2024-10-28-07-14-05-44_ab6c4a494f5f354113de683b4ea3527b](https://github.com/user-attachments/assets/84eacd3c-4684-4d39-9a79-c9a27d27a9aa)

**Comment by danielrivard** [comment]
I don't even know what MyVaillant is and how this relates to Innova?

What model unit do you have from Innova?

What is a circuit? Is it the water temperature of an AirLeaf fancoil?

This integration does nothing with any numbering, it just receives the data from the internal API of the unit. So I don't think there is not much to help you.

**Comment by peedign** [comment]
very sorry my bad - wrong repository... please close...

**Comment by danielrivard** [comment]
No worries.
