### ISSUE TITLE
I can add a fancoil but it does not add the device.

### ISSUE THREAD

**Issue by lu-zero** [danielrivard/homeassistant-innova#241]
Have some airleaf fancoils, I tried adding 4 and they were added successfully, then I tried to add a 5th and it claims it worked, it added the 5 usual entities, but not the device.

<img width="688" alt="image" src="https://github.com/user-attachments/assets/6ac100d2-2d1f-4399-97c0-1dea503a5354">

Trying to delete and re-add leads to the same outcome.

**Comment by danielrivard** [comment]
It is usually due to it having the same serial number as another of the devices

See this comment from a past issue:
https://github.com/danielrivard/homeassistant-innova/issues/187#issuecomment-2040065106

**Comment by lu-zero** [comment]
Looks like home assistant took its time to sync up if the device is removed and added back. It seems working now
