### ISSUE TITLE
Sleep mode

### ISSUE THREAD

**Issue by XaviosTheBoss** [danielrivard/homeassistant-innova#28]
Hello,

Thank you for this integration, it works like a charm. Do you think it will be possible to include the sleep mode feature to this integration later ?

Thanks.

**Comment by danielrivard** [comment]
Hi, it could be possible as there is a command for it, but I am not sure how it would fit in homeassistant, maybe using the preset modes https://developers.home-assistant.io/docs/core/entity/climate/#presets?

Is this how you would have a need for it?

**Comment by danielrivard** [comment]
Thanks @JD-c0de for contributing a change to make Sleep Mode available. The code is merged and I will prepare a release later today to publish to HACS.
