### ISSUE TITLE
Auto Mode always shows Idle in the card.

### ISSUE THREAD

**Issue by danielrivard** [danielrivard/homeassistant-innova#4]
![image](https://user-images.githubusercontent.com/2893453/168440614-528e0324-54bd-4441-b888-d95757d3499d.png)

I don't know if the unit can provide the current working mode it is using when set to Auto (Cooling vs Fan vs Heat).

**Comment by cybert79** [comment]
I don't think this is easy to change,... its imported from  homeassistant.components.climate.const.
The state IDLE is there, and so this means changing the IDLE state in the  homeassistant.components.climate lib
