### ISSUE TITLE
Make Scan Interval configurable

### ISSUE THREAD

**Issue by danielrivard** [danielrivard/homeassistant-innova#61]
**Is your feature request related to a problem? Please describe.**
Device scan interval is hardcoded to 10 minutes.

**Describe the solution you'd like**
It would be nice that anyone could configure it whatever value they prefer.

**Comment by LarsMudde** [comment]
Hi @danielrivard,

I've written some code to be able to do this, but I can't push it (403 forbidden) can you allow me to push to a branch so I can make a pull request for this and you can review it when you have time?

Regards,

Lars

**Comment by danielrivard** [comment]
Hello @LarsMudde, please follow github's guide on contributions using forks to submit a pull request. I will happily review it.

https://docs.github.com/en/get-started/exploring-projects-on-github/contributing-to-a-project

**Comment by LarsMudde** [comment]
Thank you, it's been a while since I did any contributions to a public project. https://github.com/danielrivard/homeassistant-innova/pull/224
