### ISSUE TITLE
The innovative air conditioner turns off the wifi after a certain time

### ISSUE THREAD

**Issue by Dhy19971** [danielrivard/homeassistant-innova#84]
**Describe the bug**
The innovative air conditioner turns off the wifi after a certain time

**To Reproduce**
Disconnect the power

Reconnect the power

wait a certain amount of time (a few tens of minutes)

wifi is not available

**Expected behavior**
May the connection with Hassio remain stable

**Comment by danielrivard** [comment]
The wifi chip on those units are really finicky.  I am not sure how to actually improve this.

The integration currently polls the unit every 10 minutes to avoid overloading it. I have plans to make that number configurable, so that you could increase it.
